### ISSUE TITLE
API Endpoints

### ISSUE THREAD

**Issue by wobenzym** [dvuckovic/BusPlus#1]
Malo sam se zaludeo BusPlusom. Da li imas sacuvane Endpointe i dalje za njihov API? Pozdrav

**Comment by dvuckovic** [comment]
Ja ne znam ni za kakve endpointe/API koje nudi BusPlus. Prema mom iskustvu, u pitanju je privatan servis privatne firme, tako da ne verujem da uopste razmiljaju o otvaranju istog.

Naravno, ako primetis da se ovo promeni, slobodno javi.

Poz,
D.
